[default]
timeout = 120

[snwelfare_kakao]
title = "성남시지역사회보장협의체 ─ 카카오톡 채널"
url = "https://pf.kakao.com/_kCBqxl"
entrySelector = "div.wrap_post"
titleSelector = "p.desc_post"
linkSelector = "span.txt_time a"
contentSelector = "p.desc_post"
DateSelector = "span.txt_time a"
DateFormat = "MM월 dd일 a hh:mm"
imageSelector = "a.link_thumb div.wrap_thumb, div.post_card div.wrap_thumb img.img_thumb"
waitUntil = "networkidle"

#[yongin_linktree]
#title = "용인시 ─ 링크트리"
#url = "https://linktr.ee/yicity"
#entrySelector = "div.sc-dQppl.jjdMus"
#titleSelector = "p[class='sc-hBEYos Button__StyledText-sc-uh5tyw-0 cqgIKE rsIfq']"
#linkSelector = "a[class='sc-hHftDr StyledButton-sc-686c3k-0 egoGPQ dLjCyh']"

#[naverpost_yongin]
#title = "용인시청 ─ 네이버 포스트"
#url = "https://m.post.naver.com/my.naver?memberNo=5374901"
#entrySelector = "ul.lst_feed li._cds.check_visible"
#titleSelector = "strong.tit_feed.ell"
#linkSelector = "div.text_area a.link_end"
#imageSelector = "div.image_area a img"
#contentSelector = "p.text_feed.ell"
#waitUntil = "networkidle"

#[naverpost_yongin_news]
#title = "용인시청 ─ 용인소식"
#url = "https://m.post.naver.com/my/series/detail.naver?seriesNo=265767&memberNo=5374901"
#entrySelector = "#el_list_container ul ul li"
#titleSelector = "div.spot_post_name span.ell"
#linkSelector = "a[href]"
#imageSelector = "img"
#contentSelector = "span.writer_name"

#[naverpost_yongin_tour]
#title = "용인시청 ─ 용인관광"
#url = "https://m.post.naver.com/my/series/detail.naver?seriesNo=265770&memberNo=5374901"
#entrySelector = "#el_list_container ul ul li"
#titleSelector = "div.spot_post_name span.ell"
#linkSelector = "a[href]"
#imageSelector = "img"
#contentSelector = "span.writer_name"

#[naverpost_yongin_life]
#title = "용인시청 ─ 용인생활"
#url = "https://m.post.naver.com/my/series/detail.naver?seriesNo=265785&memberNo=5374901"
#entrySelector = "#el_list_container ul ul li"
#titleSelector = "div.spot_post_name span.ell"
#linkSelector = "a[href]"
#imageSelector = "img"
#contentSelector = "span.writer_name"

#[naverpost_yongin_cook]
#title = "용인시청 ─ 용인요리"
#url = "https://m.post.naver.com/my/series/detail.naver?seriesNo=470006&memberNo=5374901"
#entrySelector = "#el_list_container ul ul li"
#titleSelector = "div.spot_post_name span.ell"
#linkSelector = "a[href]"
#imageSelector = "img"
#contentSelector = "span.writer_name"
